### ISSUE TITLE
Potential for skipping updated scsb partner files due to timestamps

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1402] opened 2021-06-08 19:15 UTC
Some analysis is needed here. We may have a potential for missing scsb partner update files due to the way full dump files are packaged.

The start / end times on the full dump event reflect the creating of the event in bibdata, not the create times of the partner files on S3.

Also, the fact that all the partner dumps from all the partner institutions are grouped together in one full dump, but aren't necessarily generated on the same day, could be an issue.

We may need to split out the full dump into multiple full dumps, one per partner institution, and update the indexing to ensure we get each one.

We may also want to update the event start / end to equal the create time from the s3 bucket, so that we can use that timestamp when locating update files from that point on.

**Comment by tpendragon** [comment] 2021-06-24 19:29
The issue is:

1. A full dump is made on date A
2. We pull the dump down on date B
3. We (right now) pull all events between B-C.

We might miss the timeframe between A-B.

**Comment by christinach** [comment] 2021-07-06 15:04
closed by #1468

**Closed by christinach** 2021-07-06 15:04 UTC
Labels: alma-implementation, bug
