### ISSUE TITLE
New Facet: Princeton-digitized content

### ISSUE THREAD

**Issue by escowles** [pulibrary/bibdata#2039] opened 2022-12-05 18:30 UTC
### User story
I would like to limit my search results to items that Princeton has digitized. Some scenarios we've discussed:
* differentiating our holdings from licensed content
* separating digitized content from physical resources
* viewing all locally-digitized content in the context of the Catalog that allows filtering by subject, date, etc. facets not available in Figgy

### Re-index required?

- [ ] Full re-index
- [x] Partial re-index
- [ ] No re-indexing required

### Implementation notes, if any
@mzelesky  is currently investigating adding digital inventory to items in Alma when an object in Figgy is completed. This would make it very easy to add this facet.

Approved by DSSG in December 2020

**Comment by ellen-aa** [comment] 2024-08-08 13:41
Hi all, I have a use case that I would like to add to this ticket (rather than create a new one). I also want to mention that addressing the digital inventory would allow us to move forward on ticket #1599 and #1757, as well as this one. Regarding the digital inventory, @christinach also mentioned in a Slack message that:
Using this feature will help us to:
1. Use a facet to filter the digital inventory.
2. Look into the indexed solr document that the catalog is using and then ‘send a request to’ figgy for the viewer if the resource exists in the digital inventory (instead of requesting Alma).
3. Easier decision to move the viewer on the top of the record page.
4.  and more things that I don’t remember right now.

My use case: PUL recently digitized [this title](https://catalog.princeton.edu/catalog/9932093003506421) for some collaborators overseas. When I searched for the title by the author's name, on the [results page](https://catalog.princeton.edu/?f[author_s][]=Obeyesekere%2C+Ranjini), it looks as though we only have the physical copy. It also doesn't come up when you select the Online facet. See screenshot below: 
<img width="1260" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFZDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c63cc36aad8ac9f77346578177f526fc230378f0/image.png" alt="image.png" />

**Comment by ellen-aa** [comment] 2024-08-12 15:08
@christinach, is this the same issue as orangelight #1599? If so, can we close one?

**Comment by christinach** [comment] 2024-08-12 15:34
> @christinach, is this the same issue as orangelight #1599? If so, can we close one?

@ellen-aa @caroldh https://github.com/pulibrary/bibdata/pull/1599 is a different ticket. Also [bibdata#1599](https://github.com/pulibrary/bibdata/pull/1599) is closed. 
Tickets that have a location name update come as a request from the Alma Tech team when there is an update in a location in Alma. In the catalog we index the 'external name' of the Alma location. In Alma locations have an 'external name' and an 'internal name' . For example see a most recent [alma location name ticket](https://github.com/pulibrary/bibdata/issues/2426).

**Comment by christinach** [comment] 2024-08-12 15:41
@ellen-aa @caroldh now I see that you were asking for [orangelight#1599](https://github.com/pulibrary/orangelight/issues/1599). The previous link took me to bibdata#1599. 
Yes, we can close this ticket as duplicate of https://github.com/pulibrary/orangelight/issues/1599

**Closed by christinach** 2024-08-12 15:41 UTC
Labels: feature, DSSG approved, att-dacs-collab, digital inventory, PO (high value)
