### ISSUE TITLE
Do not display the "Delete" column on the Events page if not logged in

### ISSUE THREAD

**Issue by kelynch** [pulibrary/bibdata#1666] opened 2021-09-24 17:58 UTC
The delete action [here](https://bibdata.princeton.edu/events) is only available to authenticated users, but the delete button is always visible.  This should only display if the user is authenticated.

**Comment by christinach** [comment] 2021-09-27 12:51
duplicate of https://github.com/pulibrary/bibdata/issues/615

**Closed by christinach** 2021-09-27 12:51 UTC
