### ISSUE TITLE
Document how to clear failed batches in the sidekiq UI

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#2109] opened 2023-03-24 21:48 UTC
Document how to clear failed batches in the sidekiq UI. If we dont clear them they will go away in 4 weeks or more.

https://bibdata.princeton.edu/sidekiq/batches

**Comment by rladdusaw** [comment] 2024-04-16 15:20
Duplicate of #2178

**Closed by rladdusaw** 2024-04-16 15:20 UTC
Labels: documentation, maintenance
