### ISSUE TITLE
RecapBoundwithsProcessingJob will not include all records

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/bibdata#1463] opened 2021-06-30 19:26 UTC
Most constituent records don’t have any holdings and so won't be included in a recap publishing job. We won't have them in order to cache them.

Need to consult with @mzelesky to determine the best logic -- use the script he wrote as a starting point for auditing / adjusting the logic we have.

**Comment by christinach** [comment] 2021-08-05 16:30
@mzelesky: this is not needed before the end of August

**Comment by carolyncole** [comment] 2021-11-30 14:39
Duplicate of #1373

**Closed by carolyncole** 2021-11-30 14:39 UTC
