### ISSUE TITLE
Add patron_group_charged in the get_items_for_bib method

### ISSUE THREAD

**Issue by christinach** [pulibrary/bibdata#850] opened 2020-10-07 19:01 UTC
child of #751 

https://bibdata.princeton.edu/bibliographic/426420/items

**Comment by christinach** [comment] 2020-10-22 16:53
blocked by #844

**Comment by hackartisan** [comment] 2021-01-06 19:01
blocked pending determination of how we will implement CDL from the Alma side

**Comment by hackartisan** [comment] 2021-03-18 14:50
close as a duplicate of #903

**Closed** 2021-03-18 14:50 UTC
Labels: alma-implementation, blocked
